### PR TITLE
feat(Statistic): Get cases/deaths from current region and worldwide

### PR DESCRIPTION
**Pull request by bestog**
I have searched long to find suitable APIs. For Germany (region) and worldwide it works.
Unfortunately there are no numbers for Recovered in Germany.
I would extend the function if I find a better API.

### CODE REVIEW

**Comment by Utzel-Butzel** [comment]
@bestog Can you make the the Pull-request into the develop branch? Many thanks!

**Comment by bestog** [comment]
Yes. https://github.com/wirewirewirewire/pandoa/pull/33

**Comment by E3V3A** [comment]
`curl "https://corona-stats.online/Germany?minimal=true"`

**Comment by bestog** [comment]
> `curl "https://corona-stats.online/Germany?minimal=true"`

Thank you. 
But for Germany we need the regions (Thuringia, ...) - I can't find the regions in your api.
But I will take the api, because it contains more data for Worldwide, than the previous.

**Pull request closed without merging**
